# Generated by Django 4.0.3 on 2024-01-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityCode', models.CharField(max_length=3)),
                ('cityName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelCode', models.CharField(max_length=10)),
                ('hotelName', models.CharField(max_length=255)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='demo.city')),
            ],
        ),
    ]
