# Generated by Django 4.0.3 on 2024-01-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_csv_type_alter_csv_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
