# Generated by Django 4.0.3 on 2024-01-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.city'),
        ),
    ]
