# Generated by Django 4.0.3 on 2024-01-10 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100),
        ),
    ]
